[tool.poetry]
name = "jinko-sdk"
version = "0.5.2"
description = "A Python package containing jinko_helpers, jinko_stats, and crabbit modules aimed to be used with Jinko.ai API"
authors = ["SSE Team <oss@novainsilico.ai>"]
readme = "README.md"
packages = [
    { include = "jinko_helpers" },
    { include = "crabbit" },
    { include = "jinko_stats" },
    { include = "jinko_nn" },
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pandas = "^2.2.2"
requests = "^2.25.1"
tqdm = "^4.66.5"
scipy = "^1.15.3"

# Optional dependencies declared here
freia = { version = "^0.2", optional = true }
torch = { version = "^2.4.1", optional = true }
scikit-learn = { version = "^1.5.2", optional = true }
seaborn = { version = "^0.13.2", optional = true }
matplotlib = { version = "^3.9.2", optional = true }

[tool.poetry.extras]
jinko_nn = ["freia", "torch", "scikit-learn", "seaborn", "matplotlib"]

[tool.poetry.group.dev.dependencies]
datamodel-code-generator = { extras = ["http"], version = "^0.26.3" }
black = { version = "^24.4.2" }
pylint = "^2.14.0"
pytest = "^8.3.3"
pytest-cov = "^3.0.0"

[tool.coverage.run]
source = ["jinko_helpers"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
